# Numpy

## Numpy Ndarray: объект многомерного массива

Объект ndarray для представления
N-мерного массива; это быстрый и гибкий контейнер для хранения больших
наборов данных в  Python

In [1]:
import numpy as np

In [5]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

У любого массива есть атрибут shape – кортеж, описывающий размер по каждому измерению,
и атрибут dtype – объект, описывающий тип данных в массиве

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

## Создание ndarray

Проще всего создать массив с помощью функции array. Она принимает любой
объект, похожий на последовательность (в том числе другой массив), и порождает новый массив NumPy, содержащий переданные данные. Например, такое
преобразование можно проделать со списком

In [8]:
data1 = [6, 7.5, 8, 0, 1]

In [9]:
arr1 = np.array(data1)

In [10]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Вложенные последовательности, например список списков одинаковой
длины, можно преобразовать в многомерный массив

In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [12]:
arr2 = np.array(data2)

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Поскольку data2 – список списков, массив NumPy arr2 имеет два измерения,
а его форма выведена из данных. В этом легко убедиться, прочитав атрибуты
ndim и shape

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

Если явно не задано иное (подробнее об этом ниже), то функция np.array пытается самостоятельно определить подходящий тип данных для создаваемого
массива. Этот тип данных хранится в  специальном объекте dtype; например,
в примерах выше имеем

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int64')

Помимо numpy.array, существует еще ряд функций для создания массивов.
Например, numpy.zeros и  numpy.ones создают массивы заданной длины или формы, состоящие из нулей и единиц соответственно, а numpy.empty создает массив,
не инициализируя его элементы. Для создания многомерных массивов нужно
передать кортеж, описывающий форму

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.empty((2, 3, 2))

array([[[5.0121555e-310, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000]],

       [[0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000]]])

Предполагать, что numpy.empty возвращает массив из одних нулей, небезопасно. Часто возвращается массив, содержащий
неинициализированный мусор,  – как в  примере выше. Эту
функцию следует использовать, только если вы собираетесь заполнить новый массив данными.



---



Функция numpy.arange – вариант встроенной в  Python функции range, только
возвращаемым значением является массив:

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Тип данных для ndarray

In [24]:
arr1 = np.array([1, 2, 3], dtype = np.float64)

In [25]:
arr1.dtype

dtype('float64')

In [27]:
arr2 = np.array([1, 2, 3], dtype = np.int32)

In [28]:
arr2.dtype

dtype('int32')

Можно явно преобразовать, или привести, массив одного типа к другому,
воспользовавшись методом astype

In [29]:
arr = np.array([1, 2, 3, 4, 5])

In [30]:
arr.dtype

dtype('int64')

In [31]:
float_arr = arr.astype(np.float64)

In [34]:
float_arr

array([1., 2., 3., 4., 5.])

In [35]:
float_arr.dtype

dtype('float64')

In [36]:
float_arr_int = float_arr.astype(np.int32)

In [37]:
float_arr_int

array([1, 2, 3, 4, 5], dtype=int32)

In [39]:
float_arr_int.dtype

dtype('int32')

При вызове astype всегда создается новый массив (данные копируются), даже если новый dtype не отличается от старого

## Арифметические операции с массивами NumPy

Массивы важны, потому что позволяют выразить операции над совокупностями данных без выписывания циклов for. Обычно это называется векторизацией. Любая арифметическая операция над массивами одинакового размера
применяется к соответственным элементам

In [58]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [59]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [60]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [61]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Арифметические операции, в  которых участвует скаляр, применяются
к каждому элементу массива

In [62]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [63]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

Сравнение массивов одинакового размера дает булев массив

In [68]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [69]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [70]:
arr2 == arr

array([[False, False, False],
       [False, False, False]])

Операции между массивами разного размера называются укладыванием

## Индексирование и вырезание

Индексирование массивов NumPy – обширная тема, поскольку подмножество
массива или его отдельные элементы можно выбрать различными способами.
С одномерными массивами все просто; на поверхностный взгляд, они ведут
себя как списки Python

In [71]:
arr = np.arange(10)

In [72]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr[5:8]

array([5, 6, 7])

In [74]:
arr[5:8] = 12

In [75]:
arr[5:8]

array([12, 12, 12])

Как видите, если присвоить скалярное значение срезу, как в arr[5:8] = 12, то
оно распространяется (или укладывается) на весь срез. Важнейшее отличие от встроенных в  Python списков состоит
в том, что срез массива является представлением исходного массива. Это означает, что данные на самом деле не  копируются,
а любые изменения, внесенные в представление, попадают и в
исходный массив.

In [76]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

Если теперь изменить значения в arr_slice, то изменения отразятся и на исходном массиве arr

In [77]:
arr_slice[1] = 12345

In [78]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

Присваивание неуточненному срезу [:] приводит к записи значения во все
элементы массива:


In [79]:
arr_slice[:] = 64

In [81]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

Чтобы получить копию, а  не представление среза массива,
нужно выполнить операцию копирования явно, например
arr[5:8].copy().



---



Для массивов большей размерности и вариантов тоже больше. В случае двумерного массива элемент с заданным индексом является не скаляром, а одномерным массивом

In [82]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [83]:
arr2d[2]

array([7, 8, 9])

К отдельным элементам можно обращаться рекурсивно. Но это слишком
громоздко, поэтому для выбора одного элемента можно указать список индексов через запятую.

In [85]:
arr2d[0][2]

3

In [86]:
arr2d[0, 2]

3

## Индексирование срезами

Как и  для одномерных объектов наподобие списков Python, для объектов
ndarray можно формировать срезы

In [87]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [88]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [89]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Выражение arr2d[:2] полезно читать так: «выбрать первые две строки arr2d»

In [92]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

Можно указать несколько срезов – как несколько индексов

In [93]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

При таком вырезании мы всегда получаем представления массивов с таким
же числом измерений, как у исходного. Сочетая срезы и целочисленные индексы, можно получить массивы меньшей размерности.
Например, я могу выбрать вторую строку, а в ней только первые два столбца

In [96]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
lower_dim_slice = arr2d[1, :2]

In [95]:
lower_dim_slice

array([4, 5])

## Булево индексирование