# Numpy

## Numpy Ndarray: объект многомерного массива

Объект ndarray для представления
N-мерного массива; это быстрый и гибкий контейнер для хранения больших
наборов данных в  Python

In [2]:
import numpy as np

In [3]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

У любого массива есть атрибут shape – кортеж, описывающий размер по каждому измерению,
и атрибут dtype – объект, описывающий тип данных в массиве

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

## Создание ndarray

Проще всего создать массив с помощью функции array. Она принимает любой
объект, похожий на последовательность (в том числе другой массив), и порождает новый массив NumPy, содержащий переданные данные. Например, такое
преобразование можно проделать со списком

In [6]:
data1 = [6, 7.5, 8, 0, 1]

In [7]:
arr1 = np.array(data1)

In [8]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Вложенные последовательности, например список списков одинаковой
длины, можно преобразовать в многомерный массив

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [10]:
arr2 = np.array(data2)

In [11]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Поскольку data2 – список списков, массив NumPy arr2 имеет два измерения,
а его форма выведена из данных. В этом легко убедиться, прочитав атрибуты
ndim и shape

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

Если явно не задано иное (подробнее об этом ниже), то функция np.array пытается самостоятельно определить подходящий тип данных для создаваемого
массива. Этот тип данных хранится в  специальном объекте dtype; например,
в примерах выше имеем

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int64')

Помимо numpy.array, существует еще ряд функций для создания массивов.
Например, numpy.zeros и  numpy.ones создают массивы заданной длины или формы, состоящие из нулей и единиц соответственно, а numpy.empty создает массив,
не инициализируя его элементы. Для создания многомерных массивов нужно
передать кортеж, описывающий форму

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.empty((2, 3, 2))

array([[[6.86890316e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

Предполагать, что numpy.empty возвращает массив из одних нулей, небезопасно. Часто возвращается массив, содержащий
неинициализированный мусор,  – как в  примере выше. Эту
функцию следует использовать, только если вы собираетесь заполнить новый массив данными.



---



Функция numpy.arange – вариант встроенной в  Python функции range, только
возвращаемым значением является массив:

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Тип данных для ndarray

In [20]:
arr1 = np.array([1, 2, 3], dtype = np.float64)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2 = np.array([1, 2, 3], dtype = np.int32)

In [23]:
arr2.dtype

dtype('int32')

Можно явно преобразовать, или привести, массив одного типа к другому,
воспользовавшись методом astype

In [24]:
arr = np.array([1, 2, 3, 4, 5])

In [25]:
arr.dtype

dtype('int64')

In [26]:
float_arr = arr.astype(np.float64)

In [27]:
float_arr

array([1., 2., 3., 4., 5.])

In [28]:
float_arr.dtype

dtype('float64')

In [29]:
float_arr_int = float_arr.astype(np.int32)

In [30]:
float_arr_int

array([1, 2, 3, 4, 5], dtype=int32)

In [31]:
float_arr_int.dtype

dtype('int32')

При вызове astype всегда создается новый массив (данные копируются), даже если новый dtype не отличается от старого

## Арифметические операции с массивами NumPy

Массивы важны, потому что позволяют выразить операции над совокупностями данных без выписывания циклов for. Обычно это называется векторизацией. Любая арифметическая операция над массивами одинакового размера
применяется к соответственным элементам

In [32]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [33]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [34]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [35]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Арифметические операции, в  которых участвует скаляр, применяются
к каждому элементу массива

In [36]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [37]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

Сравнение массивов одинакового размера дает булев массив

In [38]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [39]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [40]:
arr2 == arr

array([[False, False, False],
       [False, False, False]])

Операции между массивами разного размера называются укладыванием

## Индексирование и вырезание

Индексирование массивов NumPy – обширная тема, поскольку подмножество
массива или его отдельные элементы можно выбрать различными способами.
С одномерными массивами все просто; на поверхностный взгляд, они ведут
себя как списки Python

In [41]:
arr = np.arange(10)

In [42]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr[5:8]

array([5, 6, 7])

In [44]:
arr[5:8] = 12

In [45]:
arr[5:8]

array([12, 12, 12])

Как видите, если присвоить скалярное значение срезу, как в arr[5:8] = 12, то
оно распространяется (или укладывается) на весь срез. Важнейшее отличие от встроенных в  Python списков состоит
в том, что срез массива является представлением исходного массива. Это означает, что данные на самом деле не  копируются,
а любые изменения, внесенные в представление, попадают и в
исходный массив.

In [46]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

Если теперь изменить значения в arr_slice, то изменения отразятся и на исходном массиве arr

In [47]:
arr_slice[1] = 12345

In [48]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

Присваивание неуточненному срезу [:] приводит к записи значения во все
элементы массива:


In [49]:
arr_slice[:] = 64

In [50]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

Чтобы получить копию, а  не представление среза массива,
нужно выполнить операцию копирования явно, например
arr[5:8].copy().



---



Для массивов большей размерности и вариантов тоже больше. В случае двумерного массива элемент с заданным индексом является не скаляром, а одномерным массивом

In [51]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [52]:
arr2d[2]

array([7, 8, 9])

К отдельным элементам можно обращаться рекурсивно. Но это слишком
громоздко, поэтому для выбора одного элемента можно указать список индексов через запятую.

In [53]:
arr2d[0][2]

3

In [54]:
arr2d[0, 2]

3

## Индексирование срезами

Как и  для одномерных объектов наподобие списков Python, для объектов
ndarray можно формировать срезы

In [55]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [56]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [57]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Выражение arr2d[:2] полезно читать так: «выбрать первые две строки arr2d»

In [58]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

Можно указать несколько срезов – как несколько индексов

In [59]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

При таком вырезании мы всегда получаем представления массивов с таким
же числом измерений, как у исходного. Сочетая срезы и целочисленные индексы, можно получить массивы меньшей размерности.
Например, я могу выбрать вторую строку, а в ней только первые два столбца

In [60]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
lower_dim_slice = arr2d[1, :2]

In [62]:
lower_dim_slice

array([4, 5])

## Булево индексирование

Пусть имеется некоторый массив с данными и массив имен, содержащий дубликаты

In [63]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [66]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

Допустим, что каждое имя соответствует строке в массиве data и мы хотим
выбрать все строки, которым соответствует имя 'Bob'. Операции сравнения
массивов (например, ==), как и арифметические, также векторизованы. Поэтому сравнение names со строкой 'Bob' дает массив булевых величин:

In [67]:
data[names == 'Bob']

array([[4, 7],
       [0, 0]])

В следующих примерах я выбираю строки, в которых names == 'Bob', и одновременно задаю индекс столбцов

In [68]:
data[names == "Bob", 1:]

array([[7],
       [0]])

Чтобы выбрать все, кроме 'Bob', можно либо воспользоваться оператором
сравнения !=, либо применить отрицание – условие, обозначаемое знаком ~:


In [69]:
data[names != 'Bob']

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

Оператор ~ пригодится, когда требуется инвертировать массив, адресуемый
переменной:


In [70]:
cond = names == 'Bob'
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

Чтобы сформировать составное булево условие, включающее два из трех
имен, воспользуемся булевыми операторами & (И) и | (ИЛИ):

In [75]:
data[(names == 'Bob') | (names == 'Will')]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

Ключевые слова Python and и or с булевыми массивами не работают. Используйте вместо них & (и) и | (или).



---



Если значение устанавливается с применением булева массива, то значения
из массива в правой части копируются в левую часть только тогда, когда значение соответствующего элемента булева массива равно True. Например, чтобы заменить все отрицательные значения в массиве data нулями, нужно всего
лишь написать:

In [76]:
data[data < 0] = 0

In [77]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

Задать целые строки или столбцы с помощью одномерного булева массива
тоже просто:


In [78]:
data[names != ' Joe'] = 7

In [79]:
data

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

## Транспонирование массивов и перестановка осей

Транспонирование – частный случай изменения формы, при этом также возвращается представление исходных данных без какого-либо копирования.
У массивов имеется метод transpose и специальный атрибут T:

In [80]:
arr = np.arange(15).reshape((3, 5))

In [81]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [82]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Матрицы можно перемножить и  по-другому, воспользовавшись инфиксным оператором @

In [87]:
arr.T @ arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

## 4.2. Генерирование псевдослучайных чисел

Модуль numpy.random дополняет встроенный модуль random функциями, которые
генерируют целые массивы случайных чисел с различными распределениями
вероятности. Например, с помощью функции numpy.random.standard_normal можно
получить случайный массив 4×4, выбранный из стандартного нормального
распределения:

In [88]:
samples = np.random.standard_normal(size = (4, 4))

In [89]:
samples

array([[ 1.64232904, -2.22575367, -0.29417005,  0.1635876 ],
       [ 0.2659971 ,  0.64621804,  0.72053562, -0.53742292],
       [-0.27442561,  1.84319502,  0.49559051,  0.14709972],
       [ 0.94835418,  0.1707464 ,  1.21892726,  0.79889481]])

## Универсальные функции: быстрые поэлементные операции над массивами

In [90]:
arr = np.arange(10)

In [91]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [93]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

Такие u-функции называются унарными. Другие, например numpy.add или
numpy.maximum, принимают 2 массива (и потому называются бинарными) и возвращают один результирующий массив:

## Устранение дубликатов и другие теоретико-множественные операции

В NumPy имеются основные теоретико-множественные операции для одномерных массивов. Пожалуй, самой употребительной является numpy.unique, она
возвращает отсортированное множество уникальных значений в массиве:

In [97]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])

In [98]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

Функция numpy.in1d проверяет, присутствуют ли значения из одного массива
в другом, и возвращает булев массив:

In [99]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [100]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])